//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPrice.Domain.Database.SqlScripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductPrice.Domain.Database.SqlScripts.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///IF OBJECT_ID(&apos;dbo.PriceByProductId&apos;) IS NOT NULL
        ///  BEGIN
        ///    DROP FUNCTION dbo.PriceByProductId
        ///  END
        ///
        ///GO
        ///
        ///CREATE FUNCTION dbo.PriceByProductId (@ProductId uniqueidentifier)
        ///RETURNS DECIMAL
        ///	AS
        ///	BEGIN
        ///
        ///		declare @simplePrice as decimal
        ///		declare @PriceId as uniqueidentifier
        ///		declare @AllPrice as decimal
        ///		declare @TaxesPrice as decimal
        ///
        ///		SELECT  @PriceId = Products.ProductPriceId,
        ///				@simplePrice = ProductPrices.StartPrice
        ///		FROM Products
        ///		Join ProductPrices ON Products.ProductPriceId=ProductPrices.Id
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_PriceByProductId {
            get {
                return ResourceManager.GetString("dbo_PriceByProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///IF OBJECT_ID(&apos;dbo.PriceForRange&apos;) IS NOT NULL
        ///  BEGIN
        ///    DROP FUNCTION dbo.PriceForRange
        ///  END
        ///
        ///GO
        ///
        ///CREATE FUNCTION dbo.PriceForRange (@Products ProductIdTable  READONLY)
        ///RETURNS TABLE
        ///AS
        ///RETURN(
        ///	SELECT dbo.PriceByProductId(ProductId) as Price FROM @Products	
        ///);.
        /// </summary>
        internal static string dbo_PriceForRange {
            get {
                return ResourceManager.GetString("dbo_PriceForRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;dbo.ProductIdTable&apos;) IS NOT NULL
        ///  BEGIN
        ///    DROP FUNCTION dbo.ProductIdTable
        ///  END
        ///
        ///GO
        ///
        ///CREATE TYPE dbo.ProductIdTable as TABLE
        ///(
        ///	Id uniqueidentifier
        ///);.
        /// </summary>
        internal static string dbo_ProductId {
            get {
                return ResourceManager.GetString("dbo_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;dbo.ProductTaxes&apos;) IS NOT NULL
        ///  BEGIN
        ///    DROP FUNCTION dbo.ProductTaxes
        ///  END
        ///GO
        ///CREATE FUNCTION dbo.ProductTaxes (@ProductId uniqueidentifier)
        ///RETURNS TABLE
        ///	AS
        ///	RETURN(
        ///		SELECT Taxes.* FROM Taxes 
        ///		Join TaxProductPrices ON TaxProductPrices.Tax_Id = Taxes.Id
        ///		Join ProductPrices ON TaxProductPrices.ProductPrice_Id = ProductPrices.Id
        ///		Join Products ON Products.ProductPriceId = ProductPrices.Id
        ///		WHERE Products.Id = @ProductID
        ///).
        /// </summary>
        internal static string dbo_ProductTaxes {
            get {
                return ResourceManager.GetString("dbo_ProductTaxes", resourceCulture);
            }
        }
    }
}
